<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>OrderFlowBubblesTests</AssemblyName>
    <NoWarn>CA1416;NU1701;MSB3277;CS0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../SignalCache.cs" />
  </ItemGroup>
</Project>
